In [2]:
import numpy as np
import pandas as pd
import talib

# 仮のデータを作成します（実際には、あなたのデータを読み込むことになります）
# 以下のコードは例示用であり、実際のデータを使用してください。
df = pd.read_csv('./data/BTC_1m.csv')
# Dateをdatetime型に変換
df['Datetime'] = pd.to_datetime(df['Datetime'])
df.set_index('Datetime', inplace=True)


# 移動平均の計算
short_window = 40
long_window = 100
df['short_mavg'] = talib.SMA(df['Close'], timeperiod=short_window)
df['long_mavg'] = talib.SMA(df['Close'], timeperiod=long_window)

# シグナルの生成
df['signal'] = 0
df['signal'][short_window:] = np.where(df['short_mavg'][short_window:] > df['long_mavg'][short_window:], 1, 0)
df['positions'] = df['signal'].diff()

df[['Close', 'short_mavg', 'long_mavg', 'signal', 'positions']]

/tmp/ipykernel_75/3872199067.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['signal'][short_window:] = np.where(df['short_mavg'][short_window:] > df['long_mavg'][short_window:], 1, 0)

,Close,short_mavg,long_mavg,signal,positions
Datetime,,,,,
2024-02-20 00:00:00+00:00,7780113.0,NaN,NaN,0,NaN
2024-02-20 00:01:00+00:00,7780712.0,NaN,NaN,0,0.0
2024-02-20 00:02:00+00:00,7777378.0,NaN,NaN,0,0.0
2024-02-20 00:03:00+00:00,7780024.5,NaN,NaN,0,0.0
2024-02-20 00:04:00+00:00,7781959.5,NaN,NaN,0,0.0
...,...,...,...,...,...
2024-02-26 08:20:00+00:00,7721123.0,7.722443e+06,7735076.865,0,0.0
2024-02-26 08:21:00+00:00,7720225.0,7.722194e+06,7734760.140,0,0.0
2024-02-26 08:22:00+00:00,7721165.5,7.721941e+06,7734472.415,0,0.0
2024-02-26 08:24:00+00:00,7724259.0,7.721890e+06,7734219.885,0,0.0
2024-02-26 08:25:00+00:00,7725892.5,7.721901e+06,7733988.915,0,0.0

In [4]:
df[df['signal'] == 1]

,Open,High,Low,Close,Volume,Dividends,Stock Splits,short_mavg,long_mavg,signal,positions
Datetime,,,,,,,,,,,
2024-02-20 02:22:00+00:00,7764188.5,7764188.5,7764188.5,7764188.5,860094464,0.0,0.0,7.757484e+06,7756841.060,1,1.0
2024-02-20 02:23:00+00:00,7763662.0,7763662.0,7763662.0,7763662.0,0,0.0,0.0,7.758426e+06,7756639.385,1,0.0
2024-02-20 02:24:00+00:00,7761135.5,7761135.5,7761135.5,7761135.5,101449728,0.0,0.0,7.759128e+06,7756407.055,1,0.0
2024-02-20 02:25:00+00:00,7766087.0,7766087.0,7766087.0,7766087.0,0,0.0,0.0,7.759671e+06,7756230.625,1,0.0
2024-02-20 02:26:00+00:00,7766448.0,7766448.0,7766448.0,7766448.0,330039296,0.0,0.0,7.760275e+06,7756053.170,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2024-02-26 06:39:00+00:00,7746363.0,7746363.0,7746363.0,7746363.0,0,0.0,0.0,7.754674e+06,7753709.995,1,0.0
2024-02-26 06:41:00+00:00,7746151.5,7746151.5,7746151.5,7746151.5,0,0.0,0.0,7.754371e+06,7753626.085,1,0.0
2024-02-26 06:42:00+00:00,7746072.5,7746072.5,7746072.5,7746072.5,0,0.0,0.0,7.754053e+06,7753539.770,1,0.0
2024-02-26 06:45:00+00:00,7744992.5,7744992.5,7744992.5,7744992.5,0,0.0,0.0,7.753738e+06,7753441.570,1,0.0
2024-02-26 06:46:00+00:00,7746574.0,7746574.0,7746574.0,7746574.0,0,0.0,0.0,7.753473e+06,7753333.855,1,0.0

In [5]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,short_mavg,long_mavg,signal,positions
Datetime,,,,,,,,,,,
2024-02-20 00:00:00+00:00,7780113.0,7780113.0,7780113.0,7780113.0,0,0.0,0.0,NaN,NaN,0,NaN
2024-02-20 00:01:00+00:00,7780712.0,7780712.0,7780712.0,7780712.0,247201792,0.0,0.0,NaN,NaN,0,0.0
2024-02-20 00:02:00+00:00,7778306.0,7778306.0,7777378.0,7777378.0,0,0.0,0.0,NaN,NaN,0,0.0
2024-02-20 00:03:00+00:00,7780024.5,7780024.5,7780024.5,7780024.5,0,0.0,0.0,NaN,NaN,0,0.0
2024-02-20 00:04:00+00:00,7781959.5,7781959.5,7781959.5,7781959.5,383778816,0.0,0.0,NaN,NaN,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2024-02-26 08:20:00+00:00,7721123.0,7721123.0,7721123.0,7721123.0,33816576,0.0,0.0,7.722443e+06,7735076.865,0,0.0
2024-02-26 08:21:00+00:00,7720225.0,7720225.0,7720225.0,7720225.0,1121452032,0.0,0.0,7.722194e+06,7734760.140,0,0.0
2024-02-26 08:22:00+00:00,7721165.5,7721165.5,7721165.5,7721165.5,444071936,0.0,0.0,7.721941e+06,7734472.415,0,0.0
2024-02-26 08:24:00+00:00,7724259.0,7724259.0,7724259.0,7724259.0,3224240128,0.0,0.0,7.721890e+06,7734219.885,0,0.0
2024-02-26 08:25:00+00:00,7725892.5,7725892.5,7725892.5,7725892.5,0,0.0,0.0,7.721901e+06,7733988.915,0,0.0